//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace themesite
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTree
    {
        public int M_ID { get; set; }
        public int M_P_ID { get; set; }
        public string M_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public string CSS_CLASS { get; set; }
        public int SortOrder { get; set; }
    }
}
